version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/postgresql/data
    networks:
      - backend

  jira-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/jira
    restart: on-failure
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx.conf.d
    networks:
      - backend

networks:
  backend:
    driver: bridge



