version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/jira
    restart: on-failure


